### ISSUE TITLE
Cosas que dijo Ale/Matías que cambiemos

### ISSUE THREAD

**Issue by Micolucci** [silgch/DDS#3]
- [x] Hacer nuevas clases de exception
- [x] En QueMePongo se debería cambiar inline x constantes
- [x] Utilizar patrón adapter
- [ ] Analizar caso que fallen todas las APIS de clima

**Comment by nicomastroianni** [comment]
**Hacer nuevas clases de exception:** cree un paquete para que vayamos agregando las que veamos, deberiamos listar las excepciones a crear ya que hay varias, este check lo vamos a tener todo el proyecto
**En QueMePongo se debería cambiar inline x constantes:** tecnicamente ya esta, si alguien quiere/puede revisar para ver si la estoy manqueando, creo que era que yo tenia un numero a manopla en el codigo, habia algo mas??
**Utilizar patrón adapter :** creo que ya esta, si quieren chusmear por si hay algo que este mal es bien recibido jajaja
**Analizar caso que fallen todas las APIS de clima:** por lo que estuve probando, esta contemplado, si lo quieren probar mejor

Avisenme cuando puedan asi ya les hacemos check a esas malditas tareas

**Comment by Micolucci** [comment]
Minuta de Entrega 3:
-  Agregar función de guardarropas compartidos (bloquear prendas que hayan sido aceptadas para algún día si se pidiera otra sugerencia para ese día con el mismo guardarropas)
- Agregar **interfaz notificador** que notifique al usuario y utilice el clima adapter
- QueMePongo debería utilizar clima adapter y no la API directamente
